// Public surface of `@originchain/sdk`.
//
// Two clients:
//   * `OriginChainClient`      - talks to a per-tenant engine (bearer auth)
//   * `OriginChainAdminClient` - talks to the control plane (cookie + bearer)

export {
  OriginChainClient,
  OriginChainAdminClient,
  GraphMethods,
  edgeWeightKey,
  tenantIdFromEndpoint,
} from "./client.js";

export {
  ApiError,
  OCAddonRequiredError,
  OCPaymentRequiredError,
  isAddonRequiredBody,
} from "./errors.js";

export type { ApiErrorBody, AddonRequiredBody } from "./errors.js";

export type {
  AddonCallUsage,
  AddonEnableResponse,
  AddonRow,
  AdminClientOptions,
  ArchiveSegment,
  AskRequest,
  AskResponse,
  AuthResponse,
  CardSummary,
  ClientOptions,
  ConfirmPaymentBody,
  ConfirmPaymentMethodBody,
  CurrentUsageResponse,
  DijkstraResult,
  Eligibility,
  EventView,
  FetchLike,
  FtsIndexDoc,
  FtsMode,
  GraphBfsHit,
  GraphPath,
  Instance,
  LogLine,
  LogsResponse,
  MetricPoint,
  MetricSeries,
  MetricsResponse,
  MetricsSummaryResponse,
  PaymentMethodView,
  PendingPaymentResponse,
  PitrArchiveResponse,
  Plan,
  PlansResponse,
  ProvisionResponse,
  RankedHit,
  RemoveBlockedBody,
  SetupIntent,
  ShapeStat,
  SnapshotView,
  SchemaRegisterResponse,
  SchemaUsage,
  SqlAlterTable,
  SqlBuffered,
  SqlCreateFunction,
  SqlCreateIndex,
  SqlCreateProcedure,
  SqlCreateSequence,
  SqlCreateTable,
  SqlCreateView,
  SqlDelete,
  SqlDropFunction,
  SqlDropProcedure,
  SqlDropSequence,
  SqlDropTable,
  SqlDropView,
  SqlExplain,
  SqlInsert,
  SqlReq,
  SqlResp,
  SqlRespKind,
  SqlSelect,
  SqlTx,
  SqlUpdate,
  StorageBreakdown,
  Subscription,
  TenantConfiguration,
  TenantUsage,
  UsageLine,
  User,
  VecDeleteResp,
  VecHit,
  VecIndexKind,
  VecMetric,
  VecPutReq,
  VecTopkReq,
} from "./types.js";
